export const mockTasks = [
  {
    id: "weekly-review",
    title: "Plan weekly review",
    description: "Close the week with a clear view of wins and open loops.",
    priority: "low",
    tags: ["Planning"],
    dueDate: "2026-09-26",
    status: "backlog",
    order: 0,
    createdAt: "2026-09-21T09:00:00.000Z",
  },
  {
    id: "client-proposal",
    title: "Send client proposal",
    description: "Review the final scope and send the proposal for approval.",
    priority: "high",
    tags: ["Client", "Revenue"],
    dueDate: "2026-09-21",
    status: "in-progress",
    order: 0,
    createdAt: "2026-09-18T10:00:00.000Z",
  },
  {
    id: "roadmap-notes",
    title: "Shape Q4 roadmap notes",
    description: "Turn the product notes into three clear themes for the team.",
    priority: "medium",
    tags: ["Strategy", "Product", "Writing"],
    dueDate: "2026-09-24",
    status: "in-progress",
    order: 1,
    createdAt: "2026-09-20T14:00:00.000Z",
  },
  {
    id: "inbox-zero",
    title: "Reach inbox zero",
    description: "",
    priority: "low",
    tags: ["Admin"],
    dueDate: "2026-09-23",
    status: "completed",
    order: 0,
    createdAt: "2026-09-17T08:30:00.000Z",
  },
  {
    id: "focus-block",
    title: "Protect a focus block",
    description: "Reserve uninterrupted time for the most important task.",
    priority: "medium",
    tags: ["Focus", "Planning"],
    dueDate: "2026-09-25",
    status: "backlog",
    order: 1,
    createdAt: "2026-09-22T11:00:00.000Z",
  },
];
